Stop capture
tungs/timesnap pull request #56
Opened 2021-03-22 22:22 UTC by RhinoW

### Checklist
- [X] Code changes are only for the relevant bug fix or feature
- [X] New code lints (via `npm run lint`) without any errors or warnings
_(every line errors "Expected linebreaks to be 'LF' but found 'CRLF'"  which I guess is because I am on windows? No other errors)_
- [X] The corresponding issue is #32 https://github.com/tungs/timesnap/issues/32

### Description

In my use case (and Issue #32) I don't know exactly how long the capture should be before hand. 
This PR allows page to use `window.stopCapture()` to control when capture ends.

2021-03-29 04:53 UTC, tungs commented
Thanks for filing this. I like the idea of being able to stop capturing from the captured web page. There seem to be some minor issues (like typos), but my biggest concern is polluting the global namespace, so I'd prefer to use something more specific and less likely to conflict than `window.stopCapture`. I'll think about it this week.

2021-03-29 05:10 UTC, tungs reviewed
I'm still thinking about what I'd prefer the name to be instead of `window.stopCapture()`, but here are the other changes I have in mind. I'll do another review when I decide on a different name.

2021-03-29 05:10 UTC, tungs commented on index.js
>            return markerIndex < markers.length;
```suggestion
          return markerIndex < markers.length && !requestStopCapture;
```

2021-03-29 05:10 UTC, tungs commented on index.js
> +          }
```suggestion
```
Combine this with the loop condition (see line 255)

2021-04-22 14:42 UTC, RhinoW commented
This may be a better way to handle - https://github.com/tungs/timesnap/issues/24 - a **captureWhileSelectorExists** option.

2021-04-22 15:56 UTC, RhinoW commented
Decision between
* Add something like window.startTimesnap() window.stopTimesnap() methods - easy but pollutes global namespace
* Ashboys captureWhileSelectorExists idea - doesn't pollute but slightly more faff from rendered page (have to create/delete some element rather than calling direct).

2021-04-23 06:58 UTC, tungs commented
After mulling over the idea of polluting the global namespace with arbitrary names, I think a somewhat cleaner implementation is to allow the user to specify the name from the command line or config. Compared to the alternatives, this still allows for the stop functionality to be called from a command line invocation, while polluting with a user-chosen name.

2021-04-23 07:32 UTC, tungs requested changes
Instead of using the set name `stopCapture`, I think it's cleaner to allow the user to specify the name of the stop function via `config.stopFunctionName` from node or `--stop-function-name` from the command line.

The command line and node API sections of `README.md` need this addition, as does `cli.js`, though I can make these changes.

2021-04-23 07:32 UTC, tungs commented on index.js
> +        return page.exposeFunction('stopCapture', () => requestStopCapture = true);
```suggestion
        if (config.stopFunctionName) {
          return page.exposeFunction(config.stopFunctionName, () => requestStopCapture = true);
        }
```

2021-04-23 07:32 UTC, tungs commented on README.md
> +* [Control from page](#controlFromPage)
```suggestion
```
With this revision, this will be an opt in behavior, so no need for a new section

2021-04-23 07:32 UTC, tungs commented on README.md
> +
```suggestion
```
This should be moved to the command line and JavaScript API sections (also change `javasript` to `JavaScript`)

2021-04-23 07:32 UTC, tungs commented on index.js
> +        // page can call window.stopCapture to stop capture before --duration is up
```suggestion
        // page can call the function with config.stopFunctionName to stop capture before --duration is up
```

2021-06-14 01:01 UTC, merged